apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: regapp-postgres-ha
  namespace: regapp
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1
  postgresVersion: 13
  instances:
    - name: regapp-pgha1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: regapp-postgres-ha
                    postgres-operator.crunchydata.com/instance-set: regapp-pgha1
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      configuration:
      - secret:
          name: pgo-s3-conf
      # - secret:
      #     name: pgo-pgbackrest-secrets
      global:
        # repo1-cipher-type: aes-256-cbc
        # repo2-cipher-type: aes-256-cbc
        repo2-path: /pgbackrest/postgres-operator/regapp-postgres-ha/repo2
        repo2-s3-uri-style: path
      manual:
        repoName: repo2
        options:
          - --type=full
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * *"
          incremental: "0 */4 * * *"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 5Gi
      - name: repo2
        schedules:
          full: "0 1 * * *"
          incremental: "0 */4 * * *"
        s3:
          bucket: "nerc-shift-1-backups"
          endpoint: "holecs.rc.fas.harvard.edu"
          region: "us-east-1"
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-3
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: regapp-postgres-ha
                    postgres-operator.crunchydata.com/role: pgbouncer
