---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: regapp-db
  labels:
    app.kubernetes.io/name: regapp-db
spec:
  serviceName: regapp-db
  replicas: 1
  selector:
    matchLabels:
      app: regapp-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: regapp-db-container
        app: regapp-db
    spec:
      containers:
        - name: regapp-db-container
          # image: regapp-db:latest
          image: image-registry.openshift-image-registry.svc:5000/regapp/regapp-db:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: regapp-db-configmap
            - secretRef:
                name: regapp-db-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: regapp-db-volume-mount
              mountPath: /var/lib/postgresql/data
  
  volumeClaimTemplates:
  - spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ocs-storagecluster-ceph-rbd"
      resources:
        requests:
          storage: 1Gi
    metadata:
      name: regapp-db-volume-mount
      labels:
        app.kubernetes.io/name: regapp-db-volume-mount
