---
apiVersion: v1
kind: Service
metadata:
  name: regapp-db
  labels:
    app.kubernetes.io/name: regapp-db-svc
spec:
  clusterIP: None
  selector:
    app: regapp-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432