apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-culbert-pullsecret
  namespace: regapp
spec:
  encryptedData:
    .dockerconfigjson: AgAimNzHiOqTz+5MZlWRwRb8BjUdLGBS1JEJHw3PK29Lc4dKLKZjlPwEtOFnTuMaoLtwDa5lyvFV//MG1okGY9rvl70mo/RWdHcOvzNffRdYptflyQCibhR5qt+/zzd2l2us1UUpOu18DcPXjKdWIl2nqxQwj0YwNbFjtfJpFS+RMkZq6Z2GiqrF2KCzybqCuTu0R5MjnPIvjncmiFxgFsDVlbH/TSUrzMYDdC3f46KF05MFgT/ITRV/CEpsnUSgv0oj68AgdT61hsTi1qLRCAzx953aefGLeh0EW0S4n/umhf50MUsEVPEJKZJgDDRRGNKTY1lY5qUiQtjMN7tJq5YAgKvBWsCsbvf+gyUtvqN4395POqbsYWbd2BR33UGsoGxHzUxpPJA1DBe2DU4qWij/pOVyjsyo17T8RAoE2eLrgmU1NpXAQL6Z4mlLLWvNZiNpHyMkNxEq4pdITdgawz/ywL8+prKCSKIoA4pSFThWMesH46GFRbZ9G4FF6j4acAeoc9/NeUJyoKhgkAaXaOOOFl7Zbk3zQSVeWzFgoE5YXJQ5WGJ7kPt+HjmdYeJOjP0Uj/oeNRNktZGSD21iyfw3xYu3zRIYdH7UFV+tIsbpZav3MyBbSjzXXuDQdyBpVPArH2SG/qK75zXj1BNX2nI8Vgfbluw5cs76rPd1wBTePPT0eYLVMo5MCoPrN9mIMgythtZiacpJb8ctBLpARViBgAuOZfeKBFbDCVZ8cKvUgXIFcAeZc4YYIiRyjnK3jq4weKvvVd1p0TJ2USSMTNBwHgpuVUDB8hAUj6cgqNM17vQOzoStwYhN3Ex+6sAbkIyJL5aEXCRhXmPnXQO0j8mxb9zUq2MT2hRIySPi/Z8hWz0EPR5+VOOnoflZ8pEh/qpKIg/WhlXWQYU1/hnPp+c7WkYM+k07h8xNcKNlKoVSIDEy+h0uXoxLBldFrY/9LnWZocaP+8T6D+jw
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: ghcr-culbert-pullsecret
      namespace: regapp
    type: kubernetes.io/dockerconfigjson

