---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regapp-test
  template:
    metadata:
      labels:
        app: regapp-test
    spec:
      containers:
        - name: regapp-test
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "--" ]    
          args: [ "while true; do sleep 30; done;" ]
