apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-configmap-kc
data:
  OAUTH2_PROXY_LOGIN_URL: https://keycloakdev.mss.mghpcc.org/auth/realms/mss/protocol/openid-connect/auth
  OAUTH2_PROXY_REDEEM_URL: https://keycloakdev.mss.mghpcc.org/auth/realms/mss/protocol/openid-connect/token
  OAUTH2_PROXY_PROFILE_URL: https://keycloakdev.mss.mghpcc.org/auth/realms/mss/protocol/openid-connect/userinfo
  OAUTH2_PROXY_VALIDATE_URL: https://keycloakdev.mss.mghpcc.org/auth/realms/mss/protocol/openid-connect/userinfo
  OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloakdev.mss.mghpcc.org/auth/realms/mss