# skaffold.yaml
apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: nercra-skaffold
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: mghpcc/regapp-util
      context: ../containers/regapp-util
    - image: mghpcc/regapp-db
      context: ../containers/regapp-db
    - image: mghpcc/regapp
      context: ..
      sync:
        infer:
          - "apps/**"
          - "config/**"
          - "jinja2/**"
          - "manage.py"
      docker:
        dockerfile: containers/regapp/Dockerfile
deploy:
  kustomize:
    paths: 
      - regapp/overlays/dev

  kubeContext: minikube
